In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('data.csv')

In [4]:
df.head()

,Unnamed: 0,title,key,key_confidence,mode,mode_confidence,segments_pitches
0,0,b'Kindhearted Woman Blues',2.0,0.491,1.0,0.569,[[1. 1. 1. ... 1. 1. 1. ]\n [...
1,1,b'Watchie Watchie',11.0,0.471,0.0,0.468,[[0.061 0.042 0.039 ... 0.201 0.076 0.049]\n [...
2,2,b'Dying To Stay',1.0,0.835,1.0,0.477,[[0.079 0.039 0.037 ... 0.726 1. 0.17 ]\n [...
3,3,b'Beneath The Valley Of The Underdog (Album Ve...,0.0,0.434,1.0,0.587,[[0.242 0.217 0.164 ... 0.667 0.248 0.175]\n [...
4,4,b'Take Five - Live',11.0,0.652,0.0,0.253,[[1. 0.981 0.648 ... 0.635 0.601 0.403]\n [...

In [5]:
df.iloc[0]['segments_pitches']

'[[1.    1.    1.    ... 1.    1.    1.   ]\n [0.009 0.007 0.015 ... 0.011 0.019 0.032]\n [0.005 0.006 0.009 ... 0.022 0.004 0.006]\n ...\n [0.113 0.547 0.054 ... 0.023 0.058 0.181]\n [0.01  0.398 0.017 ... 0.005 0.004 0.034]\n [0.049 0.925 0.055 ... 0.02  0.092 0.086]]'

In [12]:
for i in df.iloc[0]['segments_pitches']:
    print(i)

[
[
1
.




1
.




1
.




.
.
.

1
.




1
.




1
.



]



[
0
.
0
0
9

0
.
0
0
7

0
.
0
1
5

.
.
.

0
.
0
1
1

0
.
0
1
9

0
.
0
3
2
]



[
0
.
0
0
5

0
.
0
0
6

0
.
0
0
9

.
.
.

0
.
0
2
2

0
.
0
0
4

0
.
0
0
6
]



.
.
.



[
0
.
1
1
3

0
.
5
4
7

0
.
0
5
4

.
.
.

0
.
0
2
3

0
.
0
5
8

0
.
1
8
1
]



[
0
.
0
1


0
.
3
9
8

0
.
0
1
7

.
.
.

0
.
0
0
5

0
.
0
0
4

0
.
0
3
4
]



[
0
.
0
4
9

0
.
9
2
5

0
.
0
5
5

.
.
.

0
.
0
2


0
.
0
9
2

0
.
0
8
6
]
]